"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
protos/auth.protove"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class RegisterUserRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USERNAME_FIELD_NUMBER: builtins.int
    EMAIL_FIELD_NUMBER: builtins.int
    PASSWORD_FIELD_NUMBER: builtins.int
    REPEAT_PASSWORD_FIELD_NUMBER: builtins.int
    username: builtins.str
    email: builtins.str
    password: builtins.str
    repeat_password: builtins.str
    def __init__(
        self,
        *,
        username: builtins.str = ...,
        email: builtins.str = ...,
        password: builtins.str = ...,
        repeat_password: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["email", b"email", "password", b"password", "repeat_password", b"repeat_password", "username", b"username"]) -> None: ...

global___RegisterUserRequest = RegisterUserRequest

@typing.final
class RegisterUserResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    ACCESS_TOKEN_FIELD_NUMBER: builtins.int
    REFRESH_TOKEN_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    success: builtins.bool
    access_token: builtins.str
    refresh_token: builtins.str
    message: builtins.str
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        access_token: builtins.str = ...,
        refresh_token: builtins.str = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["access_token", b"access_token", "message", b"message", "refresh_token", b"refresh_token", "success", b"success"]) -> None: ...

global___RegisterUserResponse = RegisterUserResponse

@typing.final
class LoginUserRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USERNAME_FIELD_NUMBER: builtins.int
    PASSWORD_FIELD_NUMBER: builtins.int
    username: builtins.str
    password: builtins.str
    def __init__(
        self,
        *,
        username: builtins.str = ...,
        password: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["password", b"password", "username", b"username"]) -> None: ...

global___LoginUserRequest = LoginUserRequest

@typing.final
class LoginUserResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    ACCESS_TOKEN_FIELD_NUMBER: builtins.int
    REFRESH_TOKEN_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    success: builtins.bool
    access_token: builtins.str
    refresh_token: builtins.str
    message: builtins.str
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        access_token: builtins.str = ...,
        refresh_token: builtins.str = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["access_token", b"access_token", "message", b"message", "refresh_token", b"refresh_token", "success", b"success"]) -> None: ...

global___LoginUserResponse = LoginUserResponse

@typing.final
class TokenRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    token: builtins.str
    def __init__(
        self,
        *,
        token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["token", b"token"]) -> None: ...

global___TokenRequest = TokenRequest

@typing.final
class TokenResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALID_FIELD_NUMBER: builtins.int
    USER_ID_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    valid: builtins.bool
    user_id: builtins.str
    message: builtins.str
    def __init__(
        self,
        *,
        valid: builtins.bool = ...,
        user_id: builtins.str = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "user_id", b"user_id", "valid", b"valid"]) -> None: ...

global___TokenResponse = TokenResponse

@typing.final
class SendVerifyCodeRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EMAIL_FIELD_NUMBER: builtins.int
    email: builtins.str
    def __init__(
        self,
        *,
        email: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["email", b"email"]) -> None: ...

global___SendVerifyCodeRequest = SendVerifyCodeRequest

@typing.final
class SendVerifyCodeResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    success: builtins.bool
    message: builtins.str
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "success", b"success"]) -> None: ...

global___SendVerifyCodeResponse = SendVerifyCodeResponse

@typing.final
class CheckVerifyCodeRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CODE_FIELD_NUMBER: builtins.int
    code: builtins.int
    def __init__(
        self,
        *,
        code: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["code", b"code"]) -> None: ...

global___CheckVerifyCodeRequest = CheckVerifyCodeRequest

@typing.final
class CheckVerifyCodeResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    success: builtins.bool
    message: builtins.str
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "success", b"success"]) -> None: ...

global___CheckVerifyCodeResponse = CheckVerifyCodeResponse

@typing.final
class EnableMFARequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_ID_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    user_id: builtins.str
    type: builtins.str
    def __init__(
        self,
        *,
        user_id: builtins.str = ...,
        type: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["type", b"type", "user_id", b"user_id"]) -> None: ...

global___EnableMFARequest = EnableMFARequest

@typing.final
class LoginStep1Response(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    MFA_TYPE_FIELD_NUMBER: builtins.int
    MFA_TOKEN_FIELD_NUMBER: builtins.int
    success: builtins.bool
    mfa_type: builtins.str
    mfa_token: builtins.str
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        mfa_type: builtins.str = ...,
        mfa_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["mfa_token", b"mfa_token", "mfa_type", b"mfa_type", "success", b"success"]) -> None: ...

global___LoginStep1Response = LoginStep1Response

@typing.final
class LoginStep2Response(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    ACCESS_TOKEN_FIELD_NUMBER: builtins.int
    REFRESH_TOKEN_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    success: builtins.bool
    access_token: builtins.str
    refresh_token: builtins.str
    message: builtins.str
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        access_token: builtins.str = ...,
        refresh_token: builtins.str = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["access_token", b"access_token", "message", b"message", "refresh_token", b"refresh_token", "success", b"success"]) -> None: ...

global___LoginStep2Response = LoginStep2Response

@typing.final
class EnableMFAResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    SECRET_FIELD_NUMBER: builtins.int
    OTPAUTH_URL_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    success: builtins.bool
    secret: builtins.str
    """TOTP секрет"""
    otpauth_url: builtins.str
    """для генерации QR-кода"""
    message: builtins.str
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        secret: builtins.str = ...,
        otpauth_url: builtins.str = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "otpauth_url", b"otpauth_url", "secret", b"secret", "success", b"success"]) -> None: ...

global___EnableMFAResponse = EnableMFAResponse
