# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"a\n\x13RegisterUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x17\n\x0frepeat_password\x18\x04 \x01(\t\"e\n\x14RegisterUserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x02 \x01(\t\x12\x15\n\rrefresh_token\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\"6\n\x10LoginUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"b\n\x11LoginUserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x02 \x01(\t\x12\x15\n\rrefresh_token\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\"\x1d\n\x0cTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"@\n\rTokenResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"&\n\x15SendVerifyCodeRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\":\n\x16SendVerifyCodeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"&\n\x16\x43heckVerifyCodeRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\";\n\x17\x43heckVerifyCodeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xe9\x02\n\x0b\x41uthService\x12\x45\n\x0cRegisterUser\x12\x19.auth.RegisterUserRequest\x1a\x1a.auth.RegisterUserResponse\x12<\n\tLoginUser\x12\x16.auth.LoginUserRequest\x1a\x17.auth.LoginUserResponse\x12\x38\n\rValidateToken\x12\x12.auth.TokenRequest\x1a\x13.auth.TokenResponse\x12K\n\x0eSendVerifyCode\x12\x1b.auth.SendVerifyCodeRequest\x1a\x1c.auth.SendVerifyCodeResponse\x12N\n\x0f\x43heckVerifyCode\x12\x1c.auth.CheckVerifyCodeRequest\x1a\x1d.auth.CheckVerifyCodeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERUSERREQUEST']._serialized_start=20
  _globals['_REGISTERUSERREQUEST']._serialized_end=117
  _globals['_REGISTERUSERRESPONSE']._serialized_start=119
  _globals['_REGISTERUSERRESPONSE']._serialized_end=220
  _globals['_LOGINUSERREQUEST']._serialized_start=222
  _globals['_LOGINUSERREQUEST']._serialized_end=276
  _globals['_LOGINUSERRESPONSE']._serialized_start=278
  _globals['_LOGINUSERRESPONSE']._serialized_end=376
  _globals['_TOKENREQUEST']._serialized_start=378
  _globals['_TOKENREQUEST']._serialized_end=407
  _globals['_TOKENRESPONSE']._serialized_start=409
  _globals['_TOKENRESPONSE']._serialized_end=473
  _globals['_SENDVERIFYCODEREQUEST']._serialized_start=475
  _globals['_SENDVERIFYCODEREQUEST']._serialized_end=513
  _globals['_SENDVERIFYCODERESPONSE']._serialized_start=515
  _globals['_SENDVERIFYCODERESPONSE']._serialized_end=573
  _globals['_CHECKVERIFYCODEREQUEST']._serialized_start=575
  _globals['_CHECKVERIFYCODEREQUEST']._serialized_end=613
  _globals['_CHECKVERIFYCODERESPONSE']._serialized_start=615
  _globals['_CHECKVERIFYCODERESPONSE']._serialized_end=674
  _globals['_AUTHSERVICE']._serialized_start=677
  _globals['_AUTHSERVICE']._serialized_end=1038
# @@protoc_insertion_point(module_scope)
